### ISSUE TITLE
Use cockpit's testing tools in cockpit-composer

### ISSUE THREAD

**Issue by jkozol** [osbuild/cockpit-composer#921]
**Problem**

The Selenium WebDriver based tests are difficult to maintain and will frequently fail for unknown reasons. This can be fixed by migrating our tests to cockpit's testing framework. This should provide increased stability and control over our test. Ideally, we will support both selenium and cdp tests for a period of time while the tests are gradually migrated over.

**Tasks**

- [x] Pull cdp and the files it is reliant on from cockpit into cockpit-composer
- [x] Use cockpit bots to configure a container to run cockpit-composer
- [x] Configure CI to run tests using both Selenium and cdp
- [x] Migrate tests to cdp
- [x] Remove Selenium from CI
